### ISSUE TITLE
cannot reproduce DDAIG on PACS

### ISSUE THREAD

**Issue by wyf0912** [KaiyangZhou/Dassl.pytorch#12]
Thanks for sharing the code.

However, even if I use your latest config file for PACS, I still cannot reproduce the results in the paper.

I repeat the experiments for 5-6 times in each domain. The results are shown in the following table:

art | sketch | photo | cartoon
-- | -- | -- | --
  | 76.91 |   | 72.23
79.35 | 74.39 | 93.05 | 73.17
79.64 | 74.13 | 94.91 | 74.32
82.71 | 71.61 | 92.81 | 73.12
80.03 | 75.41 | 94.01 | 72.14
82.37 | 75.1 | 94.01 | 72.1

Hope to get your reply.

**Comment by KaiyangZhou** [comment]
pls see this thread https://github.com/KaiyangZhou/Dassl.pytorch/issues/6 and check the param setting shown in the google drive link

**Comment by wyf0912** [comment]
Thanks for your reply. In fact, I used the latest and the same param setting in #6 

Maybe I can upload the log file tomorrow and hope you could help me find if there is anything wrong.

**Comment by wyf0912** [comment]
Hi, I have uploaded the log files and tensorboard files to google drive below

https://drive.google.com/drive/folders/1asUQOdn5ERcErZ1e1ApBAovu8_uh5tlz?usp=sharing

**Comment by KaiyangZhou** [comment]
looks like your results on cartoon are low, I checked the corresponding log file

you need to tune `lmda` instead of using `lmda=0.3` for all domains (it's different for different domain, which is a bit tricky)

for cartoon, perhaps use `lmda=0.5`

please have a look at the log files I uploaded, which contain the specific param setting https://drive.google.com/drive/folders/1OntjOBsUFIe3KtLjJJxCo__JAou0Vphl?usp=sharing

**Comment by wyf0912** [comment]
Thanks for your reply~
