### ISSUE TITLE
Custom Data?

### ISSUE THREAD

**Issue by kexinhuang12345** [KaiyangZhou/Dassl.pytorch#20]
Hi Kaiyang,

Thanks for this great repo! I am interested in using dassl to build several baselines for my own dataset, which is a set of tabular (vector) data from various domains. Do you have suggestions/tips/recommendations for adding our own dataset? 

Thanks a lot!

**Comment by KaiyangZhou** [comment]
I suggest you have a look at this base dataset class https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/data/datasets/base_dataset.py#L49. All you need to do is to subclass this base dataset class when constructing yours. You can give data to `train_u` if it is a domain adaptation problem, otherwise leave `train_u` empty. `val` is also optional.

Feel free to post further questions here regarding your new dataset.

**Comment by kexinhuang12345** [comment]
Thanks for the pointer! Will take a look closely
